### ISSUE TITLE
Incorrect Zarr store link provided, daily Zarr store copied instead of yearly or monthly

### ISSUE THREAD

**Issue by weiji14** [carbonplan/cmip6-web#78]
It seems like the [CMIP6 downscaling website](https://carbonplan.org/research/cmip6-downscaling?t=2015-1-1&f=7b2273223a22737370353835222c2276223a227461736d6178222c2274223a2279656172227d&active=ScenarioMIP.CCCma.CanESM5.ssp245.r1i1p1f1.day.GARD-SV.tasmax.month&center=0%2C2.842170943040401e-14&zoom=0.9600019116100899) only returns Zarr stores for daily timescales, rather than yearly or monthly.

![image](https://user-images.githubusercontent.com/23487320/229905562-22010ab8-3abf-46eb-974d-999b5eb77dd7.png)

E.g. for MRI-ESM2-0 SSP5-8.5 DeepSD, clicking on 'Copy Zarr store link' returns a URL like:

- https://cpdataeuwest.blob.core.windows.net/cp-cmip/version1/data/DeepSD/ScenarioMIP.MRI.MRI-ESM2-0.ssp585.r1i1p1f1.day.DeepSD.tasmax.zarr

Notice the 'day' part which stands for daily. What I'd expect are URLs like:

- https://cpdataeuwest.blob.core.windows.net/cp-cmip/version1/data/DeepSD/ScenarioMIP.MRI.MRI-ESM2-0.ssp585.r1i1p1f1.month.DeepSD.tasmax.zarr
- https://cpdataeuwest.blob.core.windows.net/cp-cmip/version1/data/DeepSD/ScenarioMIP.MRI.MRI-ESM2-0.ssp585.r1i1p1f1.year.DeepSD.tasmax.zarr

---

Note that for the 'raw' method, the Zarr stores for daily timescales are like so:

- https://cpdataeuwest.blob.core.windows.net/cp-cmip/cmip6/ScenarioMIP/MRI/MRI-ESM2-0/ssp585/r1i1p1f1/day/tasmax/gn/v20191108/

For the monthly timescale, they should be formatted like this:

- https://cpdataeuwest.blob.core.windows.net/cp-cmip/cmip6/ScenarioMIP/MRI/MRI-ESM2-0/ssp585/r1i1p1f1/Amon/tasmax/gn/v20191108

Notice the 'Amon' for monthly atmospheric data. If I'm not mistaken, yearly timescale doesn't exist for 'raw' from looking at https://cmip6.storage.googleapis.com/pangeo-cmip6.csv

References:
- https://pangeo-data.github.io/pangeo-cmip6-cloud/accessing_data.html
- https://tutorial.xarray.dev/intermediate/cmip6-cloud.html

**Comment by katamartin** [comment]
@weiji14 thanks for opening this issue! We decided to provide URLs for the daily data in that feature for easy access to the original GCMs and downscaled products even though monthly/yearly aggregated data are shown. As you've seen, `day` in the URL would need to be updated to `month` or `year` to access the aggregated downscaled data. We've updated the button text for improved clarity (5d846eb6b4d771164bb63a66efe2d8d92cde37e4).

You're correct that the URL structure for the original GCMs differs from the downscaled products. We computed the monthly and yearly aggregates on the raw data for the pyramids used in the web tool rather than relying on the Pangeo CMIP6 catalog, but have not included those in the products on Planetary Computer. Please reach out if those GCM aggregates are essential for the work you are building off the cmip6-downscaling products.
